server:
  port: 8080

spring:
  application:
    name: product-api
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: Vishwajeet@9909
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: zest-secret-key-very-secure-123456789
  expiration: 900000        # 15 minutes (access token)
  refresh-expiration: 604800000  # 7 days